# Generated by Django 5.2.6 on 2025-10-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="number_of_views",
            field=models.IntegerField(
                default=0,
                help_text="Введите число просмотров",
                verbose_name="Число просмотров",
            ),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="publication_attribute",
            field=models.BooleanField(default=False),
        ),
    ]
