# Generated by Django 5.2.6 on 2025-10-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_blogs_number_of_views_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogs",
            name="number_of_views",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Введите число просмотров",
                verbose_name="Число просмотров",
            ),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите превью",
                null=True,
                upload_to="blogs/image",
                verbose_name="Превью",
            ),
        ),
    ]
