# Generated by Django 5.2.6 on 2025-10-11 06:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_alter_blogs_number_of_views_alter_blogs_preview"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogs",
            old_name="publication_attribute",
            new_name="is_published",
        ),
        migrations.AlterField(
            model_name="blogs",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Введите дату создания",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="blogs",
            name="header",
            field=models.TextField(
                help_text="Введите наименование заголовка", verbose_name="Заголовок"
            ),
        ),
    ]
