# Generated by Django 5.2.6 on 2025-10-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(
                help_text="Введите цену за покупку", verbose_name="Цена за покупку"
            ),
        ),
    ]
